### ISSUE TITLE
Width and Height

### ISSUE THREAD

**Issue by mhmnbdllh** [GiovanniSalmeri/yellow-chartjs#1]
I tried to develop a web applying chartjs. Is there any way to automatically rule the width and height (dimension) without dealing with "canvasDimension": [800, 600] under the chartjs?

**Comment by GiovanniSalmeri** [comment]
From what I recall, chartjs allows two possibilities: either responsive (i.e. full width charts), or fixed dimensions (i.e. specifying fixed dimensions, with canvasDimension). What do you mean exactly with "automatically rule"? for example specifying a percentage? or would you like a handier method of specifying the dimensions (for example in a global setting)?
