### ISSUE TITLE
Display Nothing on Ver. 0.8.21

### ISSUE THREAD

**Issue by mhmadl** [GiovanniSalmeri/yellow-chartjs#2]
I use this extension to visualise numerical data on my web running Yellow Ver. 0.8.21 but it shows nothing. Before updating the core, it works well. Any suggestion?

**Comment by GiovanniSalmeri** [comment]
Thank you for the warning. I will take advantage of the vacation days to check everything.

**Comment by schulle4u** [comment]
The extension still works, however the installation settings are [slightly wrong at lines 13 and 14](https://github.com/GiovanniSalmeri/yellow-chartjs/blob/main/extension.ini#L13). You can manually upload/overwrite `system/extensions/chartjs.min.js` and `system/extensions/chartjs-init.js` from the ZIP file.

**Comment by mhmadl** [comment]
I tried installing new Yellow core and install Chartjs extension running in localhost. It displays nothing. I manually upload/overwrite system/extensions/chartjs.min.js and system/extensions/chartjs-init.js from the ZIP file and it displays nothing.

**Comment by mhmadl** [comment]
It works well finally. Thanks to @GiovanniSalmeri and @schulle4u for their kindness.

**Comment by mhmadl** [comment]
It seems that some configuration do not work as in the previous Yellow core. The chartjs in latest Yellow cannot recognise "title": {"display": true, "text": "Chart 1"} options. I decide to switch back to Yellow 0.8.68 which works best. Thanks for noticing. Keep the great work up.

**Comment by GiovanniSalmeri** [comment]
I will double-check this extension as soon as possible. Thank you for using it!
